apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootcrudoperation-deployment
  labels:
    app: springbootcrudoperation
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springbootcrudoperation
  template:
    metadata:
      labels:
        app: springbootcrudoperation
    spec:
      containers:
      - name: springbootcrudoperation
        image: dunkdock/springbootcrudoperation:latest_1
        ports:
        - containerPort: 80
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://studentdb.cbsw4u0s2wwg.us-east-1.rds.amazonaws.com:5432/studentdb"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "postgres"
        
