apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootcrudoperation-deployment
  labels:
    app: springbootcrudoperation
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springbootcrudoperation
  template:
    metadata:
      labels:
        app: springbootcrudoperation
    spec:
      containers:
      - name: springbootcrudoperation
        image: dunkdock/springbootcrudoperation:latest_5
        ports:
        - containerPort: 80

        
